### ISSUE TITLE
Checkbox widget link broken

### ISSUE THREAD

**Issue by krey** [QuantStack/ipysheet#65] opened 2019-03-05 22:08 UTC
Related to https://github.com/QuantStack/ipysheet/issues/64

```python
import ipywidgets as widgets
import ipysheet
from traitlets import HasTraits, Bool, link

mysheet = ipysheet.Sheet(rows=2, columns=2)

checkbox_kwargs = dict(
    layout={'width': '1em', 'height': '1em'},
    indent=False,
    value=True
)

checkbox_cell_kwargs = dict(
    column_start=0, column_end=0,
    type='widget'
)

checkbox_cells = tuple(
    ipysheet.Cell(value=widgets.Checkbox(**checkbox_kwargs), row_start=i, row_end=i, **checkbox_cell_kwargs)
    for i in range(2)
) 

mysheet.cells = checkbox_cells

class CheckboxStates(HasTraits):
    row1 = Bool()
    row2 = Bool()
    
model = CheckboxStates()

link((model, 'row1'), (checkbox_cells[0].value, 'value'))
link((model, 'row2'), (checkbox_cells[1].value, 'value'))

mysheet
```
When I run ```model.row1 = True``` the corresponding checkbox updates and vice versa, as expected.
Entering some text into B1, say, "breaks" the link between ```model.row1``` and ```checkbox_cells[0].value.value```. There is no error message.

**Comment by martinRenou** [comment] 2019-03-06 08:42
I feel like it is somewhat related to https://github.com/QuantStack/ipysheet/issues/56 and it was fixed two days ago, I tried your example and I can't reproduce what you see using `master`. 
We plan to make a patch release soon.

**Comment by martinRenou** [comment] 2019-03-06 08:54
Here is the same example that does not use the `Checkbox` widget (see [my comment](https://github.com/QuantStack/ipysheet/issues/64#issuecomment-470021165) in your other issue)

```python
import ipywidgets as widgets
import ipysheet
from traitlets import HasTraits, Bool, link

mysheet = ipysheet.Sheet(rows=2, columns=2)

checkbox_cell_kwargs = dict(
    column_start=0, column_end=0,
    type='checkbox'
)

checkbox_cells = tuple(
    ipysheet.Cell(value=False, row_start=i, row_end=i, **checkbox_cell_kwargs)
    for i in range(2)
) 

mysheet.cells = checkbox_cells

class CheckboxStates(HasTraits):
    row1 = Bool()
    row2 = Bool()
    
model = CheckboxStates()

link((model, 'row1'), (checkbox_cells[0], 'value'))
link((model, 'row2'), (checkbox_cells[1], 'value'))

mysheet
```

It's basically the same, but not using the `Checkbox` widget. This time the cell type is "checkbox", not "widget". It is not documented **yet** but those are the supported cell types:
- checkbox (for boolean values)
- text
- date
- numerical
- password
- widget

**Comment by krey** [comment] 2019-03-06 16:28
Thanks @martinRenou, I missed https://github.com/QuantStack/ipysheet/issues/56, seems quite similar, yes.

**Comment by martinRenou** [comment] 2019-03-11 10:12
Is it fixed with the new release?

**Comment by martinRenou** [comment] 2019-03-12 15:37
It should be fixed in the last release. Please feel free to re-open it if you encounter the issue again

**Closed by martinRenou** 2019-03-12 15:37 UTC

**Comment by krey** [comment] 2019-03-13 23:59
It's fixed, thank you!
