### ISSUE TITLE
Support for numbers in scientific/exponential notation?

### ISSUE THREAD

**Issue by JuanCab** [QuantStack/ipysheet#119] opened 2019-05-06 20:20 UTC
Is there any way ipysheet could support number_formating in scientific notation (like '0.00e+00' or some such thing?  I would like to use this for students creating plots and they have to enter some very small and very large numbers, scientific notation would be helpful for cleanly showing the values.

**Comment by martinRenou** [comment] 2019-05-07 06:12
We currently use Handsontable for rendering the table which uses [NumbroJS old format](http://numbrojs.com/old-format.html) for number formatting, I don't see any support for scientific notation here.

I would like ipysheet to use [d3-format](https://github.com/d3/d3-format) for number formatting, this one has scientific notation, and it is used by ipywidgets for the slider readout so we will have the same formatting conventions.

**Comment by martinRenou** [comment] 2019-05-07 07:50
This is a kind of a duplicate of this one: #104

**Closed by martinRenou** 2019-05-07 07:51 UTC
Labels: enhancement
